### ISSUE TITLE
NoMethodError: undefined method `protocol' for nil:NilClass

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [gavinkflam/lightbox2-rails#5]
No errors in development mode, but when I deploy via Capistrano I get this error during asset precompile:

``` ruby
NoMethodError: undefined method `protocol' for nil:NilClass
  (in /home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/lightbox2-rails-2.7.1/vendor/assets/stylesheets/lightbox.css.erb)
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:227:in `compute_asset_host'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:143:in `asset_path'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:91:in `asset_path'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:162:in `asset_url'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:299:in `image_url'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/lightbox2-rails-2.7.1/vendor/assets/stylesheets/lightbox.css.erb:4:in `block in singleton class'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/lightbox2-rails-2.7.1/vendor/assets/stylesheets/lightbox.css.erb:-5:in `instance_eval'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/lightbox2-rails-2.7.1/vendor/assets/stylesheets/lightbox.css.erb:-5:in `singleton class'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/lightbox2-rails-2.7.1/vendor/assets/stylesheets/lightbox.css.erb:-7:in `__tilt_4856280'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in `block in evaluate'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `evaluate'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `each'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:16:in `initialize'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:37:in `init_with'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/asset.rb:24:in `from_hash'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:54:in `cache_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/user_account/rails_deployments/www/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
```

**Comment by JakeTheSnake3p0** [comment]
Looking at other issues with this same error on the web I'm guessing it's because you're using `image_url` in your CSS assets. Without a `request` object, trying to issue a full URL is wrong. There are a couple of pull requests on this repository that I think would resolve this issue.

**Comment by gavinkflam** [comment]
Nice to have your feedback Jake. The latest 2.8.2 version should have solved the issue.

Hope to hear from you in the future.
